---
- hosts: localhost
  vars:
    wp_path: "{{ lookup('aws_ssm', 'wp_path', region=vars['default_region']) }}"
    default_region: ca-central-1
  tasks:
    - name: Update the OS
      yum:
        name: '*'
        state: latest
    - name: Install the necessary packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - httpd
        - mariadb
        - amazon-efs-utils
        - python-pip
    - name: Install Boto3
      pip:
        name: boto3
    - name: Install PHP from Amazon repos
      command: amazon-linux-extras install -y php{{ php_version }}
      vars:
        php_version: "{{ lookup('aws_ssm', 'php_version', region=vars['default_region']) }}"
    - name: Enable Apache service
      systemd:
        name: httpd
        enabled: yes
        state: started
    - name: Mount an EFS filesystem
      mount:
        path: "{{ wp_path }}"
        src: "{{ fs_path }}:/"
        fstype: efs
        state: mounted
      vars:
        fs_path: "{{ lookup('aws_ssm', 'fs_path', region=vars['default_region']) }}"
    - name: Install WP CLI tool
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: "0755"
    - name: WP installation checker 1
      command: wp core is-installed
      register: is_installed1
      ignore_errors: yes
      args:
        chdir: "{{ wp_path }}"
    - name: Download WP CORE
      command: wp core download
      when: is_installed1.rc > 0
      args:
        chdir: "{{ wp_path }}"
    - name: WP installation checker 2
      command: wp core is-installed
      register: is_installed2
      ignore_errors: yes
      args:
        chdir: "{{ wp_path }}"
    - name: Config WordPress
      command: wp core config --dbname="{{ wp_db_name }}" --dbuser="{{ wp_db_username }}" --dbpass="{{ mysql_root_password }}" --dbhost="{{ mysql_host }}"
      when: is_installed2.rc > 0
      args:
        chdir: "{{ wp_path }}"
      vars:
        wp_db_name: "{{ lookup('aws_ssm', 'wp_db_name', region=vars['default_region']) }}"
        wp_db_username: "{{ lookup('aws_ssm', 'wp_db_username', region=vars['default_region']) }}"
        mysql_root_password: "{{ lookup('aws_ssm', 'mysql_root_password', region=vars['default_region']) }}"
        mysql_host: "{{ lookup('aws_ssm', 'mysql_host', region=vars['default_region']) }}"
    - name: WP installation checker 3
      command: wp core is-installed
      register: is_installed3
      ignore_errors: yes
      args:
        chdir: "{{ wp_path }}"
    - name: Install WordPress
      command: wp core install --url="{{ wp_domain }}" --title="{{ wp_title }}" --admin_user="{{ wp_admin_username }}" --admin_password="{{ wp_admin_password }}" --admin_email="{{ wp_admin_email }}"
      when: is_installed3.rc > 0
      args:
        chdir: "{{ wp_path }}"
      vars:
        wp_domain: "{{ lookup('aws_ssm', 'wp_domain', region=vars['default_region']) }}"
        wp_title: "{{ lookup('aws_ssm', 'wp_title', region=vars['default_region']) }}"
        wp_admin_username: "{{ lookup('aws_ssm', 'wp_admin_username', region=vars['default_region']) }}"
        wp_admin_password: "{{ lookup('aws_ssm', 'wp_admin_password', region=vars['default_region']) }}"
        wp_admin_email: "{{ lookup('aws_ssm', 'wp_admin_email', region=vars['default_region']) }}"
    - name: Add user ec2-user to apache group
      user:
        name: ec2-user
        groups: apache
        append: yes
    - name: Change directory permission
      file:
        path: "{{ www_path }}"
        group: apache
        owner: ec2-user
        recurse: yes
        state: directory
        mode: u=rwX,g=rwX,o=rX
      vars:
        www_path: "{{ lookup('aws_ssm', 'www_path', region=vars['default_region']) }}"
      
